name: toDoList deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: secrets

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v5

      - name: 🔍 Debug secrets
        run: |
          echo "HOST está vazio? ${{ secrets.VPS_HOST == '' }}"
          echo "USER está vazio? ${{ secrets.VPS_USER == '' }}"
          echo "KEY está vazio? ${{ secrets.VPS_SSH_KEY == '' }}"
          echo "Tamanho do HOST: ${#VPS_HOST}"
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}

      - name: 🔑 Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 80
          script: |
            cd /home/projects/meu-app
            git pull origin main
            docker compose down
            docker compose up -d --build
            echo "✅ Deploy concluído!"
